Misc cleanup
Signed-off-by: Carson Cook <carson.cook@ibm.com>

diff --git a/.github/workflows/ci-tests.yml b/.github/workflows/ci-tests.yml
--- a/.github/workflows/ci-tests.yml
+++ b/.github/workflows/ci-tests.yml
@@ -15,7 +15,8 @@ env:
   MARIST_HOST: zzow01.zowe.marist.cloud
   MARIST_SSH_PORT: 22
   MARIST_TMP_DIRECTORY: /ZOWE/tmp
-  MARIST_TEST_DIRECTORY: /ZOWE/tmp/${{ github.run_id }}_${{ github.run_number }}
+  MARIST_TEST_DIRECTORY: /ZOWE/tmp/files-integration-test-${{ github.run_id }}_${{ github.run_number }}
+  MARIST_FILE_SETUP_SCRIPT: prepare-integration-test-folders.sh
   ZOSMF_PORT: 10443
   GATEWAY_PORT: 7554
   FILES_PORT: 8443
@@ -111,14 +112,14 @@ jobs:
         run: |
           sshpass -e sftp -o BatchMode=no -o StrictHostKeyChecking=no -o PubkeyAuthentication=no -b - -P ${{ env.MARIST_SSH_PORT }} ${{ secrets.SSH_MARIST_USERNAMEP }}@${{ env.MARIST_HOST }} << EOF
             cd ${{ env.MARIST_TMP_DIRECTORY }}
-            put scripts/prepare-integration-test-folders.sh
+            put scripts/${{ env.MARIST_FILE_SETUP_SCRIPT }}
           EOF
           sshpass -e ssh -tt -o StrictHostKeyChecking=no -o PubkeyAuthentication=no -p ${{ env.MARIST_SSH_PORT }} ${{ secrets.SSH_MARIST_USERNAMEP }}@${{ env.MARIST_HOST }} << EOF
             cd ${{ env.MARIST_TMP_DIRECTORY }}
-            iconv -f ISO8859-1 -t IBM-1047 prepare-integration-test-folders.sh > prepare-integration-test-folders.sh.new
-            mv prepare-integration-test-folders.sh.new prepare-integration-test-folders.sh && chmod +x prepare-integration-test-folders.sh
-            ./prepare-integration-test-folders.sh "${{ env.MARIST_TEST_DIRECTORY }}_v1" || { echo "[prepare-integration-test-folders v1] failed"; exit 1; }
-            ./prepare-integration-test-folders.sh "${{ env.MARIST_TEST_DIRECTORY }}_v2" || { echo "[prepare-integration-test-folders v2] failed"; exit 1; }
+            iconv -f ISO8859-1 -t IBM-1047 ${{ env.MARIST_FILE_SETUP_SCRIPT }} > ${{ env.MARIST_FILE_SETUP_SCRIPT }}.new
+            mv ${{ env.MARIST_FILE_SETUP_SCRIPT }}.new ${{ env.MARIST_FILE_SETUP_SCRIPT }} && chmod +x ${{ env.MARIST_FILE_SETUP_SCRIPT }}
+            ./${{ env.MARIST_FILE_SETUP_SCRIPT }} "${{ env.MARIST_TEST_DIRECTORY }}_v1" || { echo "[${{ env.MARIST_FILE_SETUP_SCRIPT }} v1] failed"; exit 1; }
+            ./${{ env.MARIST_FILE_SETUP_SCRIPT }} "${{ env.MARIST_TEST_DIRECTORY }}_v2" || { echo "[${{ env.MARIST_FILE_SETUP_SCRIPT }} v2] failed"; exit 1; }
           EOF
         env:
           SSHPASS: ${{ secrets.SSH_MARIST_PASSWORDP }}
@@ -147,7 +148,7 @@ jobs:
         run: |
           sshpass -e ssh -tt -o StrictHostKeyChecking=no -o PubkeyAuthentication=no -p ${{ env.MARIST_SSH_PORT }} ${{ secrets.SSH_MARIST_USERNAMEP }}@${{ env.MARIST_HOST }} << EOF
             cd ${{ env.MARIST_TMP_DIRECTORY }}
-            [ -f "prepare-integration-test-folders.sh" ] && rm prepare-integration-test-folders.sh
+            [ -f "${{ env.MARIST_FILE_SETUP_SCRIPT }}" ] && rm ${{ env.MARIST_FILE_SETUP_SCRIPT }}
             [ -d "${{ env.MARIST_TEST_DIRECTORY }}_v1" ] && rm -rf ${{ env.MARIST_TEST_DIRECTORY }}_v1
             [ -d "${{ env.MARIST_TEST_DIRECTORY }}_v2" ] && rm -rf ${{ env.MARIST_TEST_DIRECTORY }}_v2
           EOF
