Use env var for SSHPASS
Signed-off-by: Carson Cook <carson.cook@ibm.com>

diff --git a/.github/workflows/ci-tests.yml b/.github/workflows/ci-tests.yml
--- a/.github/workflows/ci-tests.yml
+++ b/.github/workflows/ci-tests.yml
@@ -108,16 +108,20 @@ jobs:
 
       - name: Prepare server side files
         run: |
-          SSHPASS=${{ secrets.SSH_MARIST_PASSWORDL }} sshpass -e sftp -o BatchMode=no -o StrictHostKeyChecking=no -o PubkeyAuthentication=no -b - -P ${{ env.MARIST_SSH_PORT }} ${{ secrets.SSH_MARIST_USERNAMEL }}@${{ env.MARIST_HOST }} << EOF
-          put scripts/prepare-integration-test-folders.sh
+          echo "START"
+          sshpass -e sftp -o BatchMode=no -o StrictHostKeyChecking=no -o PubkeyAuthentication=no -b - -P ${{ env.MARIST_SSH_PORT }} ${{ secrets.SSH_MARIST_USERNAMEL }}@${{ env.MARIST_HOST }} << EOF
+            put scripts/prepare-integration-test-folders.sh
           EOF
-          SSHPASS=${{ secrets.SSH_MARIST_PASSWORDL }} sshpass -e ssh -tt -o StrictHostKeyChecking=no -o PubkeyAuthentication=no -p ${{ env.MARIST_SSH_PORT }} ${{ secrets.SSH_MARIST_USERNAMEL }}@${{ env.MARIST_HOST }} << EOF
-          cd ~ && \
-            (iconv -f ISO8859-1 -t IBM-1047 prepare-integration-test-folders.sh > prepare-integration-test-folders.sh.new) && mv prepare-integration-test-folders.sh.new prepare-integration-test-folders.sh && chmod +x prepare-integration-test-folders.sh
-          ./prepare-integration-test-folders.sh "${{ env.MARIST_TEST_DIRECTORY }}_v1" || { echo "[prepare-integration-test-folders v1] failed"; exit 1; }
-          ./prepare-integration-test-folders.sh "$${{ env.MARIST_TEST_DIRECTORY }}_v2" || { echo "[prepare-integration-test-folders v2] failed"; exit 1; }
-          echo "[prepare-integration-test-folders] succeeds" && exit 0
+          echo "HERE"
+          sshpass -e ssh -tt -o StrictHostKeyChecking=no -o PubkeyAuthentication=no -p ${{ env.MARIST_SSH_PORT }} ${{ secrets.SSH_MARIST_USERNAMEL }}@${{ env.MARIST_HOST }} << EOF
+            cd ~ && \
+              (iconv -f ISO8859-1 -t IBM-1047 prepare-integration-test-folders.sh > prepare-integration-test-folders.sh.new) && mv prepare-integration-test-folders.sh.new prepare-integration-test-folders.sh && chmod +x prepare-integration-test-folders.sh
+            ./prepare-integration-test-folders.sh "${{ env.MARIST_TEST_DIRECTORY }}_v1" || { echo "[prepare-integration-test-folders v1] failed"; exit 1; }
+            ./prepare-integration-test-folders.sh "$${{ env.MARIST_TEST_DIRECTORY }}_v2" || { echo "[prepare-integration-test-folders v2] failed"; exit 1; }
+            echo "[prepare-integration-test-folders] succeeds" && exit 0
           EOF
+        env:
+          SSHPASS: ${{ secrets.SSH_MARIST_PASSWORDL }}
 
       - name: Integration tests for v1 - LTPA
         run: >
@@ -136,6 +140,10 @@ jobs:
           -Pserver.username=${{ secrets.SSH_MARIST_USERNAMEL }}
           -Pserver.password=${{ secrets.SSH_MARIST_PASSWORDL }}
           -Ptest.version=2
+
+      - name: Clean up integration test files # TODO implement this
+        run: |
+          echo "CLEANUP"
 
       - name: Output Files API logs
         if: always()
